# Generated by Django 3.1.4 on 2021-02-14 22:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('nigeria', 'Nigeria'), ('other africa', 'Other Africa'), ('non africa', 'Non africa')], default='select', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='profile',
            name='trade',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mansory', 'Mansory'), ('furniture', 'Furniture'), ('welding', 'Welding'), ('automobile', 'Automobile'), ('computer', 'Computer')], default='mansory', max_length=45),
        ),
    ]
