# Generated by Django 3.1.4 on 2021-02-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
